"""
Nutrition Estimator Service using Google AI (Gemini) API

This service estimates nutritional information for recipes based on ingredients.
"""

import logging
import os
import json
import httpx
from typing import List, Optional
from pydantic import BaseModel


logger = logging.getLogger(__name__)


class IngredientInput(BaseModel):
    """Input model for a single ingredient with quantity."""
    name: str
    quantity: float
    unit: str


class NutritionData(BaseModel):
    """Nutritional information returned by the AI."""
    calories: float
    protein: float
    carbs: float
    fats: float


class NutritionEstimationError(Exception):
    """Custom exception for nutrition estimation errors."""
    def __init__(self, message: str, is_rate_limited: bool = False):
        self.message = message
        self.is_rate_limited = is_rate_limited
        super().__init__(self.message)


class NutritionEstimator:
    """
    Service for estimating nutritional information using Google's Gemini AI.
    """
    
    GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemma-3-27b-it:generateContent"
    
    def __init__(self):
        self.api_key = os.getenv("GOOGLE_AI_API_KEY")
        if not self.api_key:
            raise ValueError("GOOGLE_AI_API_KEY environment variable is not set")
    
    def _format_ingredients_text(self, ingredients: List[IngredientInput]) -> str:
        """Format ingredients into a readable string for the prompt."""
        return " ".join(
            f"{ing.name} {ing.quantity} {ing.unit}"
            for ing in ingredients
        )
    
    def _build_prompt(self, ingredients: List[IngredientInput], servings: int = 1) -> str:
        """Build the prompt for the AI model."""
        ingredients_text = self._format_ingredients_text(ingredients)
        return f"""
            You are a nutrition calculator.

            Task:
            Estimate nutrition per serving based on the ingredients provided.

            Rules:
            - Output JSON only
            - No explanations or comments
            - Use numeric values (floats)
            - Units: calories in kcal, macros in grams
            - If information is missing, estimate reasonably

            Output format:
            {{"calories":0,"protein":0,"carbs":0,"fats":0}}

            Ingredients:
            {ingredients_text}
            Servings:
            {servings}
            """.strip()
    
    def _parse_response(self, response_data: dict) -> NutritionData:
        """Parse the AI response and extract nutrition data."""
        try:
            # Navigate through the Gemini API response structure
            candidates = response_data.get("candidates", [])
            if not candidates:
                raise NutritionEstimationError("No response generated by AI")
            
            content = candidates[0].get("content", {})
            parts = content.get("parts", [])
            if not parts:
                raise NutritionEstimationError("Empty response from AI")
            
            text_response = parts[0].get("text", "")
            
            # Try to extract JSON from the response
            # The AI might return the JSON directly or with some surrounding text
            json_start = text_response.find("{")
            json_end = text_response.rfind("}") + 1
            
            if json_start == -1 or json_end == 0:
                raise NutritionEstimationError(
                    f"Could not find JSON in response: {text_response}"
                )
            
            json_str = text_response[json_start:json_end]
            nutrition_dict = json.loads(json_str)
            
            # Validate and return the nutrition data
            return NutritionData(
                calories=float(nutrition_dict.get("calories", 0)),
                protein=float(nutrition_dict.get("protein", 0)),
                carbs=float(nutrition_dict.get("carbs", 0)),
                fats=float(nutrition_dict.get("fats", 0))
            )
            
        except json.JSONDecodeError as e:
            raise NutritionEstimationError(f"Failed to parse AI response as JSON: {e}")
        except (KeyError, IndexError, TypeError) as e:
            raise NutritionEstimationError(f"Unexpected response structure: {e}")
    
    async def estimate_nutrition(
        self, 
        ingredients: List[IngredientInput],
        servings: Optional[int] = 1
    ) -> NutritionData:
        """
        Estimate nutritional information for a list of ingredients.
        
        Args:
            ingredients: List of ingredients with quantities and units
            
        Returns:
            NutritionData with estimated calories, protein, carbs, and fats
            
        Raises:
            NutritionEstimationError: If the estimation fails
        """
        if not ingredients:
            raise NutritionEstimationError("No ingredients provided")
        
        prompt = self._build_prompt(ingredients, servings)
        
        # Build the request payload for Gemini API
        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.1,  # Low temperature for more consistent results
                "maxOutputTokens": 256
            }
        }
        
        url = f"{self.GEMINI_API_URL}?key={self.api_key}"
        
        async with httpx.AsyncClient(timeout=30.0) as client:
            try:
                response = await client.post(
                    url,
                    json=payload,
                    headers={"Content-Type": "application/json"}
                )
                
                # Handle rate limiting (429 status code)
                if response.status_code == 429:
                    raise NutritionEstimationError(
                        "Rate limit exceeded. Please try again later.",
                        is_rate_limited=True
                    )
                
                # Handle other error status codes
                if response.status_code != 200:
                    error_detail = response.text
                    raise NutritionEstimationError(
                        f"API request failed with status {response.status_code}: {error_detail}"
                    )
                
                response_data = response.json()
                return self._parse_response(response_data)
                
            except httpx.TimeoutException:
                raise NutritionEstimationError("Request timed out")
            except httpx.RequestError as e:
                logger.error(f"Request failed: {e}")
                raise NutritionEstimationError(f"Request failed: {e}")


# Singleton instance
_estimator: Optional[NutritionEstimator] = None


def get_nutrition_estimator() -> NutritionEstimator:
    """Get or create the nutrition estimator instance."""
    global _estimator
    if _estimator is None:
        _estimator = NutritionEstimator()
    return _estimator
