version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    # depends_on:
    #   - db
    volumes:
      - .:/app

#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data: