import json
import logging
import os
from typing import Any, Dict, Optional, Tuple
from urllib.parse import urlparse

import httpx

logger = logging.getLogger(__name__)

DEFAULT_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
DEFAULT_VERSION = "v1beta"


class GoogleAIError(Exception):
    """Base error for Google AI client failures."""


class GoogleAIRateLimitError(GoogleAIError):
    """Raised when the API responds with a rate-limit status."""


class GoogleAIRequestError(GoogleAIError):
    """Raised for request/transport/HTTP errors."""


class GoogleAIParseError(GoogleAIError):
    """Raised when parsing the API response fails."""


def _resolve_base_url(configured: Optional[str]) -> str:
    if not configured:
        return DEFAULT_BASE_URL

    parsed = urlparse(configured)
    if not parsed.scheme or not parsed.netloc:
        return DEFAULT_BASE_URL

    base = f"{parsed.scheme}://{parsed.netloc}"
    path_parts = [part for part in parsed.path.split("/") if part]
    version = None
    if path_parts and path_parts[0].startswith("v1"):
        version = path_parts[0]
    if not version:
        version = DEFAULT_VERSION
    return f"{base}/{version}"


class GoogleAIClient:
    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        self._api_key = api_key or os.getenv("GOOGLE_AI_API_KEY")
        if not self._api_key:
            raise ValueError("GOOGLE_AI_API_KEY environment variable is not set")

        configured_base = base_url or os.getenv("GEMINI_API_BASE_URL") or os.getenv("GEMINI_API_URL")
        self._base_url = _resolve_base_url(configured_base)

    @property
    def base_url(self) -> str:
        return self._base_url

    def build_generate_content_url(self, model: str) -> str:
        model = (model or "").strip()
        if not model:
            raise ValueError("model is required")
        return f"{self._base_url}/models/{model}:generateContent"

    def build_models_url(self) -> str:
        return f"{self._base_url}/models"

    async def generate_content(
        self,
        model: str,
        payload: Dict[str, Any],
        timeout: float = 30.0,
    ) -> Dict[str, Any]:
        url = self.build_generate_content_url(model)
        try:
            async with httpx.AsyncClient(timeout=timeout) as client:
                response = await client.post(
                    url,
                    params={"key": self._api_key},
                    json=payload,
                    headers={"Content-Type": "application/json"},
                )
        except httpx.TimeoutException as exc:
            raise GoogleAIRequestError("Request timed out") from exc
        except httpx.RequestError as exc:
            logger.error("Google AI request failed: %s", exc)
            raise GoogleAIRequestError(f"Request failed: {exc}") from exc

        if response.status_code == 429:
            raise GoogleAIRateLimitError("Rate limit exceeded. Please try again later.")
        if response.status_code != 200:
            raise GoogleAIRequestError(
                f"API request failed with status {response.status_code}: {response.text}"
            )

        return response.json()

    async def check_health(self, timeout: float = 10.0) -> Tuple[bool, Optional[str]]:
        try:
            async with httpx.AsyncClient(timeout=timeout) as client:
                response = await client.get(
                    self.build_models_url(),
                    params={"key": self._api_key, "pageSize": 1},
                )
        except Exception as exc:
            logger.error("Google AI health check error: %s", exc, exc_info=True)
            return False, str(exc)[:200]

        if response.status_code == 200:
            return True, None

        preview = response.text[:200] if response.text else ""
        logger.warning(
            "Google AI health check failed: %s %s", response.status_code, preview
        )
        return False, f"status_{response.status_code}: {preview}"


def extract_text(response_data: Dict[str, Any]) -> str:
    candidates = response_data.get("candidates", [])
    if not candidates:
        raise GoogleAIParseError("No response generated by AI")

    content = candidates[0].get("content", {})
    parts = content.get("parts", [])
    for part in parts:
        text = part.get("text")
        if isinstance(text, str) and text.strip():
            return text

    raise GoogleAIParseError("Empty response from AI")


def extract_json_from_text(text_response: str) -> Dict[str, Any]:
    json_start = text_response.find("{")
    json_end = text_response.rfind("}") + 1
    if json_start == -1 or json_end <= 0:
        raise GoogleAIParseError(f"Could not find JSON in response: {text_response}")
    json_str = text_response[json_start:json_end]
    try:
        return json.loads(json_str)
    except json.JSONDecodeError as exc:
        raise GoogleAIParseError(f"Failed to parse AI response as JSON: {exc}") from exc


def extract_json(response_data: Dict[str, Any]) -> Dict[str, Any]:
    return extract_json_from_text(extract_text(response_data))


_client: Optional[GoogleAIClient] = None


def get_google_ai_client() -> GoogleAIClient:
    global _client
    if _client is None:
        _client = GoogleAIClient()
    return _client
